export type PlaceTravelDetail = {
  image: string;
  lat: number;
  lng: number;
  hoursZh: string;
  hoursKo: string;
  priceZh: string;
  priceKo: string;
  metroZh: string;
  metroKo: string;
  bestZh: string;
  bestKo: string;
  tipZh: string;
  tipKo: string;
  tagsZh: string[];
  tagsKo: string[];
};

const publicSpace = {
  hoursZh: "公共区域全天开放",
  hoursKo: "공공 구역은 종일 개방",
  priceZh: "公共区域免费",
  priceKo: "공공 구역 무료",
};

const checkOfficial = {
  hoursZh: "开放时间以当天官方公告为准",
  hoursKo: "운영 시간은 당일 공식 공지 확인",
  priceZh: "部分体验可能收费",
  priceKo: "일부 체험은 유료일 수 있음",
};

export const placeTravelDetails: Record<number, PlaceTravelDetail> = {
  1: {
    image: "/images/places/nantou.jpg",
    lat: 22.5381,
    lng: 113.9105,
    ...publicSpace,
    metroZh: "地铁12号线南头古城站，步行前往南门",
    metroKo: "지하철 12호선 난터우구청역, 남문까지 도보 이동",
    bestZh: "傍晚到夜间，街巷更有氛围",
    bestKo: "해 질 무렵부터 밤까지 골목 분위기가 좋음",
    tipZh: "从南门进入，先看城门与街巷，再进入展馆和小店。",
    tipKo: "남문에서 시작해 성문과 골목을 본 뒤 전시관과 상점을 둘러보세요.",
    tagsZh: ["历史", "街巷", "拍照"],
    tagsKo: ["역사", "골목", "사진"],
  },
  2: {
    image: "/images/places/shenzhen-bay.jpg",
    lat: 22.5038,
    lng: 113.9938,
    ...publicSpace,
    metroZh: "地铁9号线深圳湾公园站，沿滨海步道步行",
    metroKo: "지하철 9호선 선전완공원역, 해안 산책로 이용",
    bestZh: "清晨观鸟，日落前后看城市天际线",
    bestKo: "아침에는 조류 관찰, 해 질 무렵에는 스카이라인 감상",
    tipZh: "海边风大，夏季建议准备遮阳用品和饮用水。",
    tipKo: "바닷바람이 강합니다. 여름에는 햇빛 차단 용품과 물을 준비하세요.",
    tagsZh: ["滨海", "观鸟", "日落"],
    tagsKo: ["해안", "조류", "노을"],
  },
  3: {
    image: "/images/places/gankeng.jpg",
    lat: 22.6507,
    lng: 114.1342,
    ...publicSpace,
    metroZh: "地铁10号线甘坑站，出站后步行前往古镇",
    metroKo: "지하철 10호선 간컹역, 역에서 고진까지 도보 이동",
    bestZh: "下午到夜间，适合连同夜景游览",
    bestKo: "오후부터 밤까지 야경과 함께 둘러보기 좋음",
    tipZh: "古镇内部岔路较多，建议先收藏二十四史书院位置。",
    tipKo: "골목이 많으니 먼저 이십사사서원 위치를 저장해 두세요.",
    tagsZh: ["客家", "古镇", "夜游"],
    tagsKo: ["객가", "고진", "야간"],
  },
  4: {
    image: "/images/places/lianhuashan.jpg",
    lat: 22.5552,
    lng: 114.0568,
    ...publicSpace,
    metroZh: "地铁3号线或4号线少年宫站，步行进入公园",
    metroKo: "지하철 3호선 또는 4호선 샤오녠궁역, 공원까지 도보",
    bestZh: "日落前一小时登顶，光线和视野更好",
    bestKo: "일몰 한 시간 전에 정상에 오르면 전망이 좋음",
    tipZh: "登顶坡度不大，但夏季白天炎热，建议傍晚前往。",
    tipKo: "경사는 완만하지만 여름 낮에는 덥습니다. 늦은 오후가 좋습니다.",
    tagsZh: ["公园", "城市全景", "日落"],
    tagsKo: ["공원", "도시 전망", "노을"],
  },
  5: {
    image: "/images/places/huaqiangbei.jpg",
    lat: 22.5443,
    lng: 114.084,
    hoursZh: "商场与档口时间不一，建议白天到访",
    hoursKo: "상가별 운영 시간이 다르므로 낮 방문 권장",
    priceZh: "街区免费，购物按需消费",
    priceKo: "거리 관람 무료, 쇼핑은 개별 결제",
    metroZh: "地铁2号线或7号线华强北站",
    metroKo: "지하철 2호선 또는 7호선 화창베이역",
    bestZh: "工作日下午，档口更集中开放",
    bestKo: "평일 오후에 상점이 가장 활발함",
    tipZh: "购买电子产品前先比价，并确认型号、保修和退换规则。",
    tipKo: "전자제품 구매 전 가격, 모델, 보증과 교환 조건을 확인하세요.",
    tagsZh: ["科创", "购物", "城市观察"],
    tagsKo: ["테크", "쇼핑", "도시 탐방"],
  },
  6: {
    image: "/images/places/dongmen.jpg",
    lat: 22.5466,
    lng: 114.1192,
    hoursZh: "街区全天可达，夜市以晚间为主",
    hoursKo: "거리는 종일 이용 가능, 야시장은 저녁 중심",
    priceZh: "街区免费，餐饮按需消费",
    priceKo: "거리 관람 무료, 음식은 개별 결제",
    metroZh: "地铁1号线或3号线老街站",
    metroKo: "지하철 1호선 또는 3호선 라오제역",
    bestZh: "傍晚以后，适合夜市和街头观察",
    bestKo: "해 질 무렵 이후 야시장과 거리 구경에 적합",
    tipZh: "人流密集，注意随身物品，并优先选择明码标价商家。",
    tipKo: "사람이 많으니 소지품을 챙기고 가격이 표시된 가게를 이용하세요.",
    tagsZh: ["夜市", "美食", "老街"],
    tagsKo: ["야시장", "음식", "옛거리"],
  },
  7: {
    image: "/images/places/futian.jpg",
    lat: 22.5364,
    lng: 114.055,
    ...checkOfficial,
    metroZh: "地铁1号线或3号线购物公园站",
    metroKo: "지하철 1호선 또는 3호선 쇼핑공원역",
    bestZh: "晴朗傍晚到入夜，城市灯光层次更丰富",
    bestKo: "맑은 날 해 질 무렵부터 야경 시간까지",
    tipZh: "观景项目可能受天气影响，出发前查看当天公告。",
    tipKo: "전망 시설은 날씨 영향을 받을 수 있으니 당일 공지를 확인하세요.",
    tagsZh: ["地标", "高空", "夜景"],
    tagsKo: ["랜드마크", "전망대", "야경"],
  },
  8: {
    image: "/images/riverside.png",
    lat: 22.546,
    lng: 114.594,
    ...publicSpace,
    metroZh: "距离市区较远，建议预约车辆或自驾",
    metroKo: "도심에서 멀어 예약 차량 또는 자가용 권장",
    bestZh: "晴天上午，预留往返交通时间",
    bestKo: "맑은 날 오전, 왕복 이동 시간을 충분히 확보",
    tipZh: "周末可能拥堵，海边天气变化快，不建议临时出发。",
    tipKo: "주말에는 정체될 수 있고 해안 날씨가 변덕스러우니 미리 계획하세요.",
    tagsZh: ["山海", "远足", "一日游"],
    tagsKo: ["산과 바다", "트레킹", "당일치기"],
  },
  9: {
    image: "/images/places/shenzhen-bay.jpg",
    lat: 22.5376,
    lng: 113.9865,
    ...checkOfficial,
    metroZh: "地铁1号线华侨城站",
    metroKo: "지하철 1호선 화차오청역",
    bestZh: "上午入园，留出半天以上",
    bestKo: "오전 입장, 반나절 이상 확보",
    tipZh: "园区面积较大，先确认当天演出时间，再安排步行路线。",
    tipKo: "규모가 크므로 공연 시간을 먼저 확인한 뒤 동선을 계획하세요.",
    tagsZh: ["主题公园", "民俗", "亲子"],
    tagsKo: ["테마파크", "민속", "가족"],
  },
  10: {
    image: "/images/places/gankeng.jpg",
    lat: 22.6522,
    lng: 114.1328,
    ...checkOfficial,
    metroZh: "地铁10号线甘坑站，进入古镇后步行",
    metroKo: "지하철 10호선 간컹역, 고진 안에서 도보 이동",
    bestZh: "下午光线柔和，适合建筑和园林拍摄",
    bestKo: "오후의 부드러운 빛이 건축과 정원 촬영에 적합",
    tipZh: "与甘坑古镇安排在同一天，移动最省时。",
    tipKo: "간컹고진과 같은 날 묶으면 이동 시간이 줄어듭니다.",
    tagsZh: ["书院", "园林", "国风"],
    tagsKo: ["서원", "정원", "전통미"],
  },
  11: {
    image: "/images/places/huaqiangbei.jpg",
    lat: 22.687,
    lng: 113.999,
    ...checkOfficial,
    metroZh: "位置偏离主要景区，建议预约车辆并确认参观安排",
    metroKo: "주요 관광지와 떨어져 있어 차량 예약과 방문 확인 필요",
    bestZh: "有公开活动或展览时前往",
    bestKo: "공개 행사나 전시가 있을 때 방문",
    tipZh: "这里不是常规商业景点，出发前必须确认是否对外开放。",
    tipKo: "일반 관광지가 아니므로 출발 전에 외부 공개 여부를 확인하세요.",
    tagsZh: ["建筑", "时尚", "预约"],
    tagsKo: ["건축", "패션", "예약"],
  },
  12: {
    image: "/images/places/shenzhen-bay.jpg",
    lat: 22.5104,
    lng: 113.9436,
    ...checkOfficial,
    metroZh: "地铁2号线或11号线后海站，步行前往海边",
    metroKo: "지하철 2호선 또는 11호선 허우하이역, 해안까지 도보",
    bestZh: "下午看展，傍晚衔接人才公园",
    bestKo: "오후 전시 관람 후 저녁에 인재공원 연계",
    tipZh: "场馆开放和展览安排可能变化，建议先确认当天信息。",
    tipKo: "전시와 개방 일정이 바뀔 수 있으니 당일 정보를 확인하세요.",
    tagsZh: ["建筑", "展览", "滨海"],
    tagsKo: ["건축", "전시", "해안"],
  },
  13: {
    image: "/images/riverside.png",
    lat: 22.596,
    lng: 114.538,
    ...checkOfficial,
    metroZh: "大鹏区域，建议预约车辆并预留返程时间",
    metroKo: "다펑 지역, 예약 차량 이용과 귀환 시간 확보 권장",
    bestZh: "晴天上午到下午，避开恶劣天气",
    bestKo: "맑은 날 오전부터 오후, 악천후 피하기",
    tipZh: "临海步道和悬崖区域要留意现场安全提示。",
    tipKo: "해안 산책로와 절벽 구간에서는 현장 안전 안내를 따르세요.",
    tagsZh: ["海湾", "度假", "拍照"],
    tagsKo: ["만", "휴양", "사진"],
  },
  14: {
    image: "/images/places/sea-world.jpg",
    lat: 22.4859,
    lng: 113.9151,
    hoursZh: "公共街区全天可达，商户时间不一",
    hoursKo: "공공 거리는 종일 이용 가능, 매장별 시간 상이",
    priceZh: "街区免费，餐饮与活动另付费",
    priceKo: "거리 관람 무료, 음식과 행사는 별도 결제",
    metroZh: "地铁2号线或12号线海上世界站",
    metroKo: "지하철 2호선 또는 12호선 해상세계역",
    bestZh: "傍晚到夜间，适合晚餐和夜景",
    bestKo: "해 질 무렵부터 밤까지 식사와 야경에 적합",
    tipZh: "先沿海边散步，再回到明华轮周边用餐。",
    tipKo: "해안 산책 후 밍화룬 주변에서 식사하는 동선이 좋습니다.",
    tagsZh: ["蛇口", "夜景", "餐饮"],
    tagsKo: ["서커우", "야경", "식사"],
  },
  15: {
    image: "/images/places/shenzhen-bay.jpg",
    lat: 22.5262,
    lng: 113.9914,
    hoursZh: "公共区域全天可达，项目时间不一",
    hoursKo: "공공 구역은 종일 이용 가능, 시설별 시간 상이",
    priceZh: "公共区域免费，演艺项目可能收费",
    priceKo: "공공 구역 무료, 공연 시설은 유료일 수 있음",
    metroZh: "地铁9号线深圳湾公园站",
    metroKo: "지하철 9호선 선전완공원역",
    bestZh: "下午到夜间，适合湿地和夜景连游",
    bestKo: "오후부터 밤까지 습지와 야경을 함께 감상",
    tipZh: "面积较大，建议先确定用餐点和离场地铁站。",
    tipKo: "구역이 넓으니 식사 장소와 귀가 지하철역을 먼저 정하세요.",
    tagsZh: ["湿地", "商业", "夜游"],
    tagsKo: ["습지", "쇼핑", "야간"],
  },
  16: {
    image: "/images/places/oh-bay.jpg",
    lat: 22.5517,
    lng: 113.8778,
    hoursZh: "滨海公园全天开放，摩天轮时间另行确认",
    hoursKo: "해안공원 종일 개방, 관람차 시간은 별도 확인",
    priceZh: "公园免费，摩天轮等项目收费",
    priceKo: "공원 무료, 관람차 등 시설은 유료",
    metroZh: "地铁5号线临海站，步行前往滨海公园",
    metroKo: "지하철 5호선 린하이역, 해안공원까지 도보",
    bestZh: "日落到亮灯后，摩天轮景观完整",
    bestKo: "일몰부터 점등 이후까지 관람차 풍경이 좋음",
    tipZh: "周末人多，返程时可以提前步行到地铁站。",
    tipKo: "주말에는 혼잡하므로 귀가 때 지하철역으로 미리 이동하세요.",
    tagsZh: ["摩天轮", "滨海", "亲子"],
    tagsKo: ["관람차", "해안", "가족"],
  },
  17: {
    image: "/images/places/futian.jpg",
    lat: 22.5414,
    lng: 114.0572,
    ...publicSpace,
    metroZh: "地铁2号线或4号线市民中心站",
    metroKo: "지하철 2호선 또는 4호선 시민중심역",
    bestZh: "傍晚连接莲花山和福田夜景",
    bestKo: "저녁에 롄화산과 푸톈 야경을 연결하기 좋음",
    tipZh: "广场开阔，夏季白天较晒，建议傍晚游览。",
    tipKo: "광장이 넓고 여름 낮에는 햇빛이 강해 저녁 방문을 권합니다.",
    tagsZh: ["中轴", "建筑", "城市"],
    tagsKo: ["도시축", "건축", "도시"],
  },
  18: {
    image: "/images/places/futian.jpg",
    lat: 22.5357,
    lng: 114.0625,
    hoursZh: "街区全天可达，商户营业时间不一",
    hoursKo: "거리는 종일 이용 가능, 매장별 영업 시간 상이",
    priceZh: "街区免费，餐饮购物按需消费",
    priceKo: "거리 관람 무료, 식사와 쇼핑은 개별 결제",
    metroZh: "地铁10号线岗厦北站或1号线岗厦站",
    metroKo: "지하철 10호선 강샤베이역 또는 1호선 강샤역",
    bestZh: "晚餐前后，适合连接福田夜景",
    bestKo: "저녁 식사 전후 푸톈 야경과 연결하기 좋음",
    tipZh: "街区分区较多，可把集合点设在明显地标旁。",
    tipKo: "구역이 넓으므로 눈에 띄는 랜드마크를 만남 장소로 정하세요.",
    tagsZh: ["街区", "餐饮", "夜景"],
    tagsKo: ["거리", "식사", "야경"],
  },
};

export const themedCollections = [
  {
    id: "first-day",
    titleZh: "第一次来深圳",
    titleKo: "선전 첫 여행",
    subtitleZh: "城市中轴、科技街区和海湾夜色",
    subtitleKo: "도시 중심축, 테크 거리와 해안 야경",
    image: "/images/places/futian.jpg",
    placeIds: [4, 17, 5, 14],
  },
  {
    id: "history",
    titleZh: "城市的旧时光",
    titleKo: "도시의 옛 시간",
    subtitleZh: "古城、客家村落与岭南街巷",
    subtitleKo: "고성, 객가 마을과 링난 골목",
    image: "/images/places/nantou.jpg",
    placeIds: [1, 3, 10, 6],
  },
  {
    id: "sunset",
    titleZh: "追一场深圳日落",
    titleKo: "선전의 노을을 따라",
    subtitleZh: "滨海步道、城市天际线和摩天轮",
    subtitleKo: "해안 산책로, 스카이라인과 관람차",
    image: "/images/places/shenzhen-bay.jpg",
    placeIds: [2, 4, 16, 14],
  },
];

export const travelToolkits = [
  {
    id: "payment",
    icon: "wallet",
    titleZh: "支付准备",
    titleKo: "결제 준비",
    bodyZh: "准备支付宝或微信支付，同时保留少量现金和实体银行卡。",
    bodyKo: "알리페이 또는 위챗페이를 준비하고 소액 현금과 실물 카드를 함께 보관하세요.",
  },
  {
    id: "transport",
    icon: "metro",
    titleZh: "地铁与打车",
    titleKo: "지하철과 택시",
    bodyZh: "优先使用地铁。打车时可把详情页中的中文地名展示给司机。",
    bodyKo: "지하철을 우선 이용하세요. 택시에서는 상세 화면의 중국어 지명을 기사에게 보여 주세요.",
  },
  {
    id: "border",
    icon: "passport",
    titleZh: "深港往返",
    titleKo: "선전-홍콩 이동",
    bodyZh: "提前确认口岸开放时间、证件和返程交通，不要只按地图距离估算。",
    bodyKo: "출입경 구역 운영 시간, 여행 서류와 귀환 교통을 미리 확인하세요. 지도 거리만으로 판단하지 마세요.",
  },
  {
    id: "network",
    icon: "network",
    titleZh: "网络与地图",
    titleKo: "통신과 지도",
    bodyZh: "出发前保存酒店中文地址、常用地点和离线资料。",
    bodyKo: "출발 전에 호텔 중국어 주소, 자주 가는 장소와 오프라인 자료를 저장하세요.",
  },
];

export const districtStories = [
  { zh: "南山", ko: "난산", noteZh: "海湾、设计与改革开放记忆", noteKo: "해안, 디자인과 개혁개방의 기억", placeIds: [1, 2, 9, 12, 14, 15] },
  { zh: "福田", ko: "푸톈", noteZh: "城市中轴、天际线与科技商业", noteKo: "도시 중심축, 스카이라인과 테크 상권", placeIds: [4, 5, 7, 17, 18] },
  { zh: "龙岗", ko: "룽강", noteZh: "客家文化与东方园林", noteKo: "객가 문화와 동양 정원", placeIds: [3, 10] },
  { zh: "大鹏", ko: "다펑", noteZh: "山海公路与海湾度假", noteKo: "산과 바다, 해안 휴양", placeIds: [8, 13] },
];

export const photoCredits = [
  "Iswzo / Wikimedia Commons / CC BY-SA 4.0",
  "Lyg 2001 / Wikimedia Commons / CC BY-SA 4.0",
  "Ermell / Wikimedia Commons / CC BY-SA 4.0",
  "Charlie fong / Wikimedia Commons / CC BY-SA 4.0",
  "Ubahnverleih / Wikimedia Commons / CC0",
  "QINGFATTIEAM 2002 / Wikimedia Commons / CC BY-SA 4.0 and CC0",
  "飞凌鱼京 / Unsplash License",
];

export function travelDetailFor(id: number) {
  return placeTravelDetails[id];
}

export function estimateTravelMinutes(fromId: number, toId: number) {
  const from = placeTravelDetails[fromId];
  const to = placeTravelDetails[toId];
  if (!from || !to) return 20;
  const lat = ((from.lat + to.lat) / 2) * (Math.PI / 180);
  const dx = (from.lng - to.lng) * 111 * Math.cos(lat);
  const dy = (from.lat - to.lat) * 111;
  const distance = Math.sqrt(dx * dx + dy * dy);
  return Math.max(8, Math.round((distance / 22) * 60 / 5) * 5);
}
